// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	GameMap          string
	Games            string
	Match            string
	MatchResult      string
	Teams            string
	TeamsStats       string
	TeamsUsers       string
	Tournaments      string
	TournamentsUsers string
	Users            string
	UsersEconomy     string
	UsersStats       string
	Vacansy          string
}{
	GameMap:          "game_map",
	Games:            "games",
	Match:            "match",
	MatchResult:      "match_result",
	Teams:            "teams",
	TeamsStats:       "teams_stats",
	TeamsUsers:       "teams_users",
	Tournaments:      "tournaments",
	TournamentsUsers: "tournaments_users",
	Users:            "users",
	UsersEconomy:     "users_economy",
	UsersStats:       "users_stats",
	Vacansy:          "vacansy",
}
