// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Match is an object representing the database table.
type Match struct {
	ID             int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	TournamentID   int64     `boil:"tournament_id" json:"tournament_id" toml:"tournament_id" yaml:"tournament_id"`
	Participant1ID int64     `boil:"participant1_id" json:"participant1_id" toml:"participant1_id" yaml:"participant1_id"`
	Participant2ID int64     `boil:"participant2_id" json:"participant2_id" toml:"participant2_id" yaml:"participant2_id"`
	MapID          int64     `boil:"map_id" json:"map_id" toml:"map_id" yaml:"map_id"`
	MatchDate      time.Time `boil:"match_date" json:"match_date" toml:"match_date" yaml:"match_date"`
	Status         bool      `boil:"status" json:"status" toml:"status" yaml:"status"`

	R *matchR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L matchL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MatchColumns = struct {
	ID             string
	TournamentID   string
	Participant1ID string
	Participant2ID string
	MapID          string
	MatchDate      string
	Status         string
}{
	ID:             "id",
	TournamentID:   "tournament_id",
	Participant1ID: "participant1_id",
	Participant2ID: "participant2_id",
	MapID:          "map_id",
	MatchDate:      "match_date",
	Status:         "status",
}

var MatchTableColumns = struct {
	ID             string
	TournamentID   string
	Participant1ID string
	Participant2ID string
	MapID          string
	MatchDate      string
	Status         string
}{
	ID:             "match.id",
	TournamentID:   "match.tournament_id",
	Participant1ID: "match.participant1_id",
	Participant2ID: "match.participant2_id",
	MapID:          "match.map_id",
	MatchDate:      "match.match_date",
	Status:         "match.status",
}

// Generated where

type whereHelperbool struct{ field string }

func (w whereHelperbool) EQ(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperbool) NEQ(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperbool) LT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperbool) LTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperbool) GT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperbool) GTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }

var MatchWhere = struct {
	ID             whereHelperint64
	TournamentID   whereHelperint64
	Participant1ID whereHelperint64
	Participant2ID whereHelperint64
	MapID          whereHelperint64
	MatchDate      whereHelpertime_Time
	Status         whereHelperbool
}{
	ID:             whereHelperint64{field: "\"match\".\"id\""},
	TournamentID:   whereHelperint64{field: "\"match\".\"tournament_id\""},
	Participant1ID: whereHelperint64{field: "\"match\".\"participant1_id\""},
	Participant2ID: whereHelperint64{field: "\"match\".\"participant2_id\""},
	MapID:          whereHelperint64{field: "\"match\".\"map_id\""},
	MatchDate:      whereHelpertime_Time{field: "\"match\".\"match_date\""},
	Status:         whereHelperbool{field: "\"match\".\"status\""},
}

// MatchRels is where relationship names are stored.
var MatchRels = struct {
	Map          string
	Tournament   string
	MatchResults string
}{
	Map:          "Map",
	Tournament:   "Tournament",
	MatchResults: "MatchResults",
}

// matchR is where relationships are stored.
type matchR struct {
	Map          *GameMap         `boil:"Map" json:"Map" toml:"Map" yaml:"Map"`
	Tournament   *Tournament      `boil:"Tournament" json:"Tournament" toml:"Tournament" yaml:"Tournament"`
	MatchResults MatchResultSlice `boil:"MatchResults" json:"MatchResults" toml:"MatchResults" yaml:"MatchResults"`
}

// NewStruct creates a new relationship struct
func (*matchR) NewStruct() *matchR {
	return &matchR{}
}

func (r *matchR) GetMap() *GameMap {
	if r == nil {
		return nil
	}
	return r.Map
}

func (r *matchR) GetTournament() *Tournament {
	if r == nil {
		return nil
	}
	return r.Tournament
}

func (r *matchR) GetMatchResults() MatchResultSlice {
	if r == nil {
		return nil
	}
	return r.MatchResults
}

// matchL is where Load methods for each relationship are stored.
type matchL struct{}

var (
	matchAllColumns            = []string{"id", "tournament_id", "participant1_id", "participant2_id", "map_id", "match_date", "status"}
	matchColumnsWithoutDefault = []string{"tournament_id", "participant1_id", "participant2_id", "map_id", "status"}
	matchColumnsWithDefault    = []string{"id", "match_date"}
	matchPrimaryKeyColumns     = []string{"id"}
	matchGeneratedColumns      = []string{}
)

type (
	// MatchSlice is an alias for a slice of pointers to Match.
	// This should almost always be used instead of []Match.
	MatchSlice []*Match
	// MatchHook is the signature for custom Match hook methods
	MatchHook func(context.Context, boil.ContextExecutor, *Match) error

	matchQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	matchType                 = reflect.TypeOf(&Match{})
	matchMapping              = queries.MakeStructMapping(matchType)
	matchPrimaryKeyMapping, _ = queries.BindMapping(matchType, matchMapping, matchPrimaryKeyColumns)
	matchInsertCacheMut       sync.RWMutex
	matchInsertCache          = make(map[string]insertCache)
	matchUpdateCacheMut       sync.RWMutex
	matchUpdateCache          = make(map[string]updateCache)
	matchUpsertCacheMut       sync.RWMutex
	matchUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var matchAfterSelectMu sync.Mutex
var matchAfterSelectHooks []MatchHook

var matchBeforeInsertMu sync.Mutex
var matchBeforeInsertHooks []MatchHook
var matchAfterInsertMu sync.Mutex
var matchAfterInsertHooks []MatchHook

var matchBeforeUpdateMu sync.Mutex
var matchBeforeUpdateHooks []MatchHook
var matchAfterUpdateMu sync.Mutex
var matchAfterUpdateHooks []MatchHook

var matchBeforeDeleteMu sync.Mutex
var matchBeforeDeleteHooks []MatchHook
var matchAfterDeleteMu sync.Mutex
var matchAfterDeleteHooks []MatchHook

var matchBeforeUpsertMu sync.Mutex
var matchBeforeUpsertHooks []MatchHook
var matchAfterUpsertMu sync.Mutex
var matchAfterUpsertHooks []MatchHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Match) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range matchAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Match) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range matchBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Match) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range matchAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Match) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range matchBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Match) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range matchAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Match) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range matchBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Match) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range matchAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Match) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range matchBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Match) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range matchAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddMatchHook registers your hook function for all future operations.
func AddMatchHook(hookPoint boil.HookPoint, matchHook MatchHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		matchAfterSelectMu.Lock()
		matchAfterSelectHooks = append(matchAfterSelectHooks, matchHook)
		matchAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		matchBeforeInsertMu.Lock()
		matchBeforeInsertHooks = append(matchBeforeInsertHooks, matchHook)
		matchBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		matchAfterInsertMu.Lock()
		matchAfterInsertHooks = append(matchAfterInsertHooks, matchHook)
		matchAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		matchBeforeUpdateMu.Lock()
		matchBeforeUpdateHooks = append(matchBeforeUpdateHooks, matchHook)
		matchBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		matchAfterUpdateMu.Lock()
		matchAfterUpdateHooks = append(matchAfterUpdateHooks, matchHook)
		matchAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		matchBeforeDeleteMu.Lock()
		matchBeforeDeleteHooks = append(matchBeforeDeleteHooks, matchHook)
		matchBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		matchAfterDeleteMu.Lock()
		matchAfterDeleteHooks = append(matchAfterDeleteHooks, matchHook)
		matchAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		matchBeforeUpsertMu.Lock()
		matchBeforeUpsertHooks = append(matchBeforeUpsertHooks, matchHook)
		matchBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		matchAfterUpsertMu.Lock()
		matchAfterUpsertHooks = append(matchAfterUpsertHooks, matchHook)
		matchAfterUpsertMu.Unlock()
	}
}

// One returns a single match record from the query.
func (q matchQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Match, error) {
	o := &Match{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for match")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Match records from the query.
func (q matchQuery) All(ctx context.Context, exec boil.ContextExecutor) (MatchSlice, error) {
	var o []*Match

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Match slice")
	}

	if len(matchAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Match records in the query.
func (q matchQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count match rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q matchQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if match exists")
	}

	return count > 0, nil
}

// Map pointed to by the foreign key.
func (o *Match) Map(mods ...qm.QueryMod) gameMapQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.MapID),
	}

	queryMods = append(queryMods, mods...)

	return GameMaps(queryMods...)
}

// Tournament pointed to by the foreign key.
func (o *Match) Tournament(mods ...qm.QueryMod) tournamentQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.TournamentID),
	}

	queryMods = append(queryMods, mods...)

	return Tournaments(queryMods...)
}

// MatchResults retrieves all the match_result's MatchResults with an executor.
func (o *Match) MatchResults(mods ...qm.QueryMod) matchResultQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"match_result\".\"match_id\"=?", o.ID),
	)

	return MatchResults(queryMods...)
}

// LoadMap allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (matchL) LoadMap(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMatch interface{}, mods queries.Applicator) error {
	var slice []*Match
	var object *Match

	if singular {
		var ok bool
		object, ok = maybeMatch.(*Match)
		if !ok {
			object = new(Match)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeMatch)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeMatch))
			}
		}
	} else {
		s, ok := maybeMatch.(*[]*Match)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeMatch)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeMatch))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &matchR{}
		}
		args[object.MapID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &matchR{}
			}

			args[obj.MapID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`game_map`),
		qm.WhereIn(`game_map.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load GameMap")
	}

	var resultSlice []*GameMap
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice GameMap")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for game_map")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for game_map")
	}

	if len(gameMapAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Map = foreign
		if foreign.R == nil {
			foreign.R = &gameMapR{}
		}
		foreign.R.MapMatches = append(foreign.R.MapMatches, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.MapID == foreign.ID {
				local.R.Map = foreign
				if foreign.R == nil {
					foreign.R = &gameMapR{}
				}
				foreign.R.MapMatches = append(foreign.R.MapMatches, local)
				break
			}
		}
	}

	return nil
}

// LoadTournament allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (matchL) LoadTournament(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMatch interface{}, mods queries.Applicator) error {
	var slice []*Match
	var object *Match

	if singular {
		var ok bool
		object, ok = maybeMatch.(*Match)
		if !ok {
			object = new(Match)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeMatch)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeMatch))
			}
		}
	} else {
		s, ok := maybeMatch.(*[]*Match)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeMatch)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeMatch))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &matchR{}
		}
		args[object.TournamentID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &matchR{}
			}

			args[obj.TournamentID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tournaments`),
		qm.WhereIn(`tournaments.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Tournament")
	}

	var resultSlice []*Tournament
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Tournament")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for tournaments")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tournaments")
	}

	if len(tournamentAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Tournament = foreign
		if foreign.R == nil {
			foreign.R = &tournamentR{}
		}
		foreign.R.Matches = append(foreign.R.Matches, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.TournamentID == foreign.ID {
				local.R.Tournament = foreign
				if foreign.R == nil {
					foreign.R = &tournamentR{}
				}
				foreign.R.Matches = append(foreign.R.Matches, local)
				break
			}
		}
	}

	return nil
}

// LoadMatchResults allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (matchL) LoadMatchResults(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMatch interface{}, mods queries.Applicator) error {
	var slice []*Match
	var object *Match

	if singular {
		var ok bool
		object, ok = maybeMatch.(*Match)
		if !ok {
			object = new(Match)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeMatch)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeMatch))
			}
		}
	} else {
		s, ok := maybeMatch.(*[]*Match)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeMatch)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeMatch))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &matchR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &matchR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`match_result`),
		qm.WhereIn(`match_result.match_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load match_result")
	}

	var resultSlice []*MatchResult
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice match_result")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on match_result")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for match_result")
	}

	if len(matchResultAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.MatchResults = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &matchResultR{}
			}
			foreign.R.Match = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.MatchID {
				local.R.MatchResults = append(local.R.MatchResults, foreign)
				if foreign.R == nil {
					foreign.R = &matchResultR{}
				}
				foreign.R.Match = local
				break
			}
		}
	}

	return nil
}

// SetMap of the match to the related item.
// Sets o.R.Map to related.
// Adds o to related.R.MapMatches.
func (o *Match) SetMap(ctx context.Context, exec boil.ContextExecutor, insert bool, related *GameMap) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"match\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"map_id"}),
		strmangle.WhereClause("\"", "\"", 2, matchPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.MapID = related.ID
	if o.R == nil {
		o.R = &matchR{
			Map: related,
		}
	} else {
		o.R.Map = related
	}

	if related.R == nil {
		related.R = &gameMapR{
			MapMatches: MatchSlice{o},
		}
	} else {
		related.R.MapMatches = append(related.R.MapMatches, o)
	}

	return nil
}

// SetTournament of the match to the related item.
// Sets o.R.Tournament to related.
// Adds o to related.R.Matches.
func (o *Match) SetTournament(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Tournament) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"match\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"tournament_id"}),
		strmangle.WhereClause("\"", "\"", 2, matchPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.TournamentID = related.ID
	if o.R == nil {
		o.R = &matchR{
			Tournament: related,
		}
	} else {
		o.R.Tournament = related
	}

	if related.R == nil {
		related.R = &tournamentR{
			Matches: MatchSlice{o},
		}
	} else {
		related.R.Matches = append(related.R.Matches, o)
	}

	return nil
}

// AddMatchResults adds the given related objects to the existing relationships
// of the match, optionally inserting them as new records.
// Appends related to o.R.MatchResults.
// Sets related.R.Match appropriately.
func (o *Match) AddMatchResults(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*MatchResult) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.MatchID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"match_result\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"match_id"}),
				strmangle.WhereClause("\"", "\"", 2, matchResultPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.MatchID = o.ID
		}
	}

	if o.R == nil {
		o.R = &matchR{
			MatchResults: related,
		}
	} else {
		o.R.MatchResults = append(o.R.MatchResults, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &matchResultR{
				Match: o,
			}
		} else {
			rel.R.Match = o
		}
	}
	return nil
}

// Matches retrieves all the records using an executor.
func Matches(mods ...qm.QueryMod) matchQuery {
	mods = append(mods, qm.From("\"match\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"match\".*"})
	}

	return matchQuery{q}
}

// FindMatch retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMatch(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*Match, error) {
	matchObj := &Match{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"match\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, matchObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from match")
	}

	if err = matchObj.doAfterSelectHooks(ctx, exec); err != nil {
		return matchObj, err
	}

	return matchObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Match) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no match provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(matchColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	matchInsertCacheMut.RLock()
	cache, cached := matchInsertCache[key]
	matchInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			matchAllColumns,
			matchColumnsWithDefault,
			matchColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(matchType, matchMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(matchType, matchMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"match\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"match\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into match")
	}

	if !cached {
		matchInsertCacheMut.Lock()
		matchInsertCache[key] = cache
		matchInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Match.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Match) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	matchUpdateCacheMut.RLock()
	cache, cached := matchUpdateCache[key]
	matchUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			matchAllColumns,
			matchPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update match, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"match\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, matchPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(matchType, matchMapping, append(wl, matchPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update match row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for match")
	}

	if !cached {
		matchUpdateCacheMut.Lock()
		matchUpdateCache[key] = cache
		matchUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q matchQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for match")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for match")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MatchSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), matchPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"match\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, matchPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in match slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all match")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Match) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no match provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(matchColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	matchUpsertCacheMut.RLock()
	cache, cached := matchUpsertCache[key]
	matchUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			matchAllColumns,
			matchColumnsWithDefault,
			matchColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			matchAllColumns,
			matchPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert match, could not build update column list")
		}

		ret := strmangle.SetComplement(matchAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(matchPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert match, could not build conflict column list")
			}

			conflict = make([]string, len(matchPrimaryKeyColumns))
			copy(conflict, matchPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"match\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(matchType, matchMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(matchType, matchMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert match")
	}

	if !cached {
		matchUpsertCacheMut.Lock()
		matchUpsertCache[key] = cache
		matchUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Match record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Match) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Match provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), matchPrimaryKeyMapping)
	sql := "DELETE FROM \"match\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from match")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for match")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q matchQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no matchQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from match")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for match")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MatchSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(matchBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), matchPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"match\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, matchPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from match slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for match")
	}

	if len(matchAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Match) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindMatch(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MatchSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MatchSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), matchPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"match\".* FROM \"match\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, matchPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in MatchSlice")
	}

	*o = slice

	return nil
}

// MatchExists checks if the Match row exists.
func MatchExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"match\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if match exists")
	}

	return exists, nil
}

// Exists checks if the Match row exists.
func (o *Match) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return MatchExists(ctx, exec, o.ID)
}
