// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// TeamsUser is an object representing the database table.
type TeamsUser struct {
	ID        int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	UserID    int64     `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	TeamID    int64     `boil:"team_id" json:"team_id" toml:"team_id" yaml:"team_id"`
	Role      string    `boil:"role" json:"role" toml:"role" yaml:"role"`
	JoinedAt  time.Time `boil:"joined_at" json:"joined_at" toml:"joined_at" yaml:"joined_at"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *teamsUserR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L teamsUserL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var TeamsUserColumns = struct {
	ID        string
	UserID    string
	TeamID    string
	Role      string
	JoinedAt  string
	UpdatedAt string
}{
	ID:        "id",
	UserID:    "user_id",
	TeamID:    "team_id",
	Role:      "role",
	JoinedAt:  "joined_at",
	UpdatedAt: "updated_at",
}

var TeamsUserTableColumns = struct {
	ID        string
	UserID    string
	TeamID    string
	Role      string
	JoinedAt  string
	UpdatedAt string
}{
	ID:        "teams_users.id",
	UserID:    "teams_users.user_id",
	TeamID:    "teams_users.team_id",
	Role:      "teams_users.role",
	JoinedAt:  "teams_users.joined_at",
	UpdatedAt: "teams_users.updated_at",
}

// Generated where

var TeamsUserWhere = struct {
	ID        whereHelperint64
	UserID    whereHelperint64
	TeamID    whereHelperint64
	Role      whereHelperstring
	JoinedAt  whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
}{
	ID:        whereHelperint64{field: "\"teams_users\".\"id\""},
	UserID:    whereHelperint64{field: "\"teams_users\".\"user_id\""},
	TeamID:    whereHelperint64{field: "\"teams_users\".\"team_id\""},
	Role:      whereHelperstring{field: "\"teams_users\".\"role\""},
	JoinedAt:  whereHelpertime_Time{field: "\"teams_users\".\"joined_at\""},
	UpdatedAt: whereHelpertime_Time{field: "\"teams_users\".\"updated_at\""},
}

// TeamsUserRels is where relationship names are stored.
var TeamsUserRels = struct {
	Team string
	User string
}{
	Team: "Team",
	User: "User",
}

// teamsUserR is where relationships are stored.
type teamsUserR struct {
	Team *Team `boil:"Team" json:"Team" toml:"Team" yaml:"Team"`
	User *User `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*teamsUserR) NewStruct() *teamsUserR {
	return &teamsUserR{}
}

func (r *teamsUserR) GetTeam() *Team {
	if r == nil {
		return nil
	}
	return r.Team
}

func (r *teamsUserR) GetUser() *User {
	if r == nil {
		return nil
	}
	return r.User
}

// teamsUserL is where Load methods for each relationship are stored.
type teamsUserL struct{}

var (
	teamsUserAllColumns            = []string{"id", "user_id", "team_id", "role", "joined_at", "updated_at"}
	teamsUserColumnsWithoutDefault = []string{"user_id", "team_id", "role"}
	teamsUserColumnsWithDefault    = []string{"id", "joined_at", "updated_at"}
	teamsUserPrimaryKeyColumns     = []string{"id"}
	teamsUserGeneratedColumns      = []string{}
)

type (
	// TeamsUserSlice is an alias for a slice of pointers to TeamsUser.
	// This should almost always be used instead of []TeamsUser.
	TeamsUserSlice []*TeamsUser
	// TeamsUserHook is the signature for custom TeamsUser hook methods
	TeamsUserHook func(context.Context, boil.ContextExecutor, *TeamsUser) error

	teamsUserQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	teamsUserType                 = reflect.TypeOf(&TeamsUser{})
	teamsUserMapping              = queries.MakeStructMapping(teamsUserType)
	teamsUserPrimaryKeyMapping, _ = queries.BindMapping(teamsUserType, teamsUserMapping, teamsUserPrimaryKeyColumns)
	teamsUserInsertCacheMut       sync.RWMutex
	teamsUserInsertCache          = make(map[string]insertCache)
	teamsUserUpdateCacheMut       sync.RWMutex
	teamsUserUpdateCache          = make(map[string]updateCache)
	teamsUserUpsertCacheMut       sync.RWMutex
	teamsUserUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var teamsUserAfterSelectMu sync.Mutex
var teamsUserAfterSelectHooks []TeamsUserHook

var teamsUserBeforeInsertMu sync.Mutex
var teamsUserBeforeInsertHooks []TeamsUserHook
var teamsUserAfterInsertMu sync.Mutex
var teamsUserAfterInsertHooks []TeamsUserHook

var teamsUserBeforeUpdateMu sync.Mutex
var teamsUserBeforeUpdateHooks []TeamsUserHook
var teamsUserAfterUpdateMu sync.Mutex
var teamsUserAfterUpdateHooks []TeamsUserHook

var teamsUserBeforeDeleteMu sync.Mutex
var teamsUserBeforeDeleteHooks []TeamsUserHook
var teamsUserAfterDeleteMu sync.Mutex
var teamsUserAfterDeleteHooks []TeamsUserHook

var teamsUserBeforeUpsertMu sync.Mutex
var teamsUserBeforeUpsertHooks []TeamsUserHook
var teamsUserAfterUpsertMu sync.Mutex
var teamsUserAfterUpsertHooks []TeamsUserHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *TeamsUser) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teamsUserAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *TeamsUser) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teamsUserBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *TeamsUser) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teamsUserAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *TeamsUser) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teamsUserBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *TeamsUser) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teamsUserAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *TeamsUser) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teamsUserBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *TeamsUser) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teamsUserAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *TeamsUser) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teamsUserBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *TeamsUser) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range teamsUserAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddTeamsUserHook registers your hook function for all future operations.
func AddTeamsUserHook(hookPoint boil.HookPoint, teamsUserHook TeamsUserHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		teamsUserAfterSelectMu.Lock()
		teamsUserAfterSelectHooks = append(teamsUserAfterSelectHooks, teamsUserHook)
		teamsUserAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		teamsUserBeforeInsertMu.Lock()
		teamsUserBeforeInsertHooks = append(teamsUserBeforeInsertHooks, teamsUserHook)
		teamsUserBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		teamsUserAfterInsertMu.Lock()
		teamsUserAfterInsertHooks = append(teamsUserAfterInsertHooks, teamsUserHook)
		teamsUserAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		teamsUserBeforeUpdateMu.Lock()
		teamsUserBeforeUpdateHooks = append(teamsUserBeforeUpdateHooks, teamsUserHook)
		teamsUserBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		teamsUserAfterUpdateMu.Lock()
		teamsUserAfterUpdateHooks = append(teamsUserAfterUpdateHooks, teamsUserHook)
		teamsUserAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		teamsUserBeforeDeleteMu.Lock()
		teamsUserBeforeDeleteHooks = append(teamsUserBeforeDeleteHooks, teamsUserHook)
		teamsUserBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		teamsUserAfterDeleteMu.Lock()
		teamsUserAfterDeleteHooks = append(teamsUserAfterDeleteHooks, teamsUserHook)
		teamsUserAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		teamsUserBeforeUpsertMu.Lock()
		teamsUserBeforeUpsertHooks = append(teamsUserBeforeUpsertHooks, teamsUserHook)
		teamsUserBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		teamsUserAfterUpsertMu.Lock()
		teamsUserAfterUpsertHooks = append(teamsUserAfterUpsertHooks, teamsUserHook)
		teamsUserAfterUpsertMu.Unlock()
	}
}

// One returns a single teamsUser record from the query.
func (q teamsUserQuery) One(ctx context.Context, exec boil.ContextExecutor) (*TeamsUser, error) {
	o := &TeamsUser{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for teams_users")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all TeamsUser records from the query.
func (q teamsUserQuery) All(ctx context.Context, exec boil.ContextExecutor) (TeamsUserSlice, error) {
	var o []*TeamsUser

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to TeamsUser slice")
	}

	if len(teamsUserAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all TeamsUser records in the query.
func (q teamsUserQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count teams_users rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q teamsUserQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if teams_users exists")
	}

	return count > 0, nil
}

// Team pointed to by the foreign key.
func (o *TeamsUser) Team(mods ...qm.QueryMod) teamQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.TeamID),
	}

	queryMods = append(queryMods, mods...)

	return Teams(queryMods...)
}

// User pointed to by the foreign key.
func (o *TeamsUser) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadTeam allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (teamsUserL) LoadTeam(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTeamsUser interface{}, mods queries.Applicator) error {
	var slice []*TeamsUser
	var object *TeamsUser

	if singular {
		var ok bool
		object, ok = maybeTeamsUser.(*TeamsUser)
		if !ok {
			object = new(TeamsUser)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTeamsUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTeamsUser))
			}
		}
	} else {
		s, ok := maybeTeamsUser.(*[]*TeamsUser)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTeamsUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTeamsUser))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &teamsUserR{}
		}
		args[object.TeamID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &teamsUserR{}
			}

			args[obj.TeamID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`teams`),
		qm.WhereIn(`teams.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Team")
	}

	var resultSlice []*Team
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Team")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for teams")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for teams")
	}

	if len(teamAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Team = foreign
		if foreign.R == nil {
			foreign.R = &teamR{}
		}
		foreign.R.TeamsUsers = append(foreign.R.TeamsUsers, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.TeamID == foreign.ID {
				local.R.Team = foreign
				if foreign.R == nil {
					foreign.R = &teamR{}
				}
				foreign.R.TeamsUsers = append(foreign.R.TeamsUsers, local)
				break
			}
		}
	}

	return nil
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (teamsUserL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTeamsUser interface{}, mods queries.Applicator) error {
	var slice []*TeamsUser
	var object *TeamsUser

	if singular {
		var ok bool
		object, ok = maybeTeamsUser.(*TeamsUser)
		if !ok {
			object = new(TeamsUser)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTeamsUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTeamsUser))
			}
		}
	} else {
		s, ok := maybeTeamsUser.(*[]*TeamsUser)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTeamsUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTeamsUser))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &teamsUserR{}
		}
		args[object.UserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &teamsUserR{}
			}

			args[obj.UserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.TeamsUsers = append(foreign.R.TeamsUsers, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.TeamsUsers = append(foreign.R.TeamsUsers, local)
				break
			}
		}
	}

	return nil
}

// SetTeam of the teamsUser to the related item.
// Sets o.R.Team to related.
// Adds o to related.R.TeamsUsers.
func (o *TeamsUser) SetTeam(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Team) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"teams_users\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"team_id"}),
		strmangle.WhereClause("\"", "\"", 2, teamsUserPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.TeamID = related.ID
	if o.R == nil {
		o.R = &teamsUserR{
			Team: related,
		}
	} else {
		o.R.Team = related
	}

	if related.R == nil {
		related.R = &teamR{
			TeamsUsers: TeamsUserSlice{o},
		}
	} else {
		related.R.TeamsUsers = append(related.R.TeamsUsers, o)
	}

	return nil
}

// SetUser of the teamsUser to the related item.
// Sets o.R.User to related.
// Adds o to related.R.TeamsUsers.
func (o *TeamsUser) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"teams_users\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, teamsUserPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &teamsUserR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			TeamsUsers: TeamsUserSlice{o},
		}
	} else {
		related.R.TeamsUsers = append(related.R.TeamsUsers, o)
	}

	return nil
}

// TeamsUsers retrieves all the records using an executor.
func TeamsUsers(mods ...qm.QueryMod) teamsUserQuery {
	mods = append(mods, qm.From("\"teams_users\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"teams_users\".*"})
	}

	return teamsUserQuery{q}
}

// FindTeamsUser retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindTeamsUser(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*TeamsUser, error) {
	teamsUserObj := &TeamsUser{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"teams_users\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, teamsUserObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from teams_users")
	}

	if err = teamsUserObj.doAfterSelectHooks(ctx, exec); err != nil {
		return teamsUserObj, err
	}

	return teamsUserObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *TeamsUser) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no teams_users provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(teamsUserColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	teamsUserInsertCacheMut.RLock()
	cache, cached := teamsUserInsertCache[key]
	teamsUserInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			teamsUserAllColumns,
			teamsUserColumnsWithDefault,
			teamsUserColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(teamsUserType, teamsUserMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(teamsUserType, teamsUserMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"teams_users\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"teams_users\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into teams_users")
	}

	if !cached {
		teamsUserInsertCacheMut.Lock()
		teamsUserInsertCache[key] = cache
		teamsUserInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the TeamsUser.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *TeamsUser) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	teamsUserUpdateCacheMut.RLock()
	cache, cached := teamsUserUpdateCache[key]
	teamsUserUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			teamsUserAllColumns,
			teamsUserPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update teams_users, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"teams_users\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, teamsUserPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(teamsUserType, teamsUserMapping, append(wl, teamsUserPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update teams_users row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for teams_users")
	}

	if !cached {
		teamsUserUpdateCacheMut.Lock()
		teamsUserUpdateCache[key] = cache
		teamsUserUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q teamsUserQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for teams_users")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for teams_users")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TeamsUserSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), teamsUserPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"teams_users\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, teamsUserPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in teamsUser slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all teamsUser")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *TeamsUser) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no teams_users provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(teamsUserColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	teamsUserUpsertCacheMut.RLock()
	cache, cached := teamsUserUpsertCache[key]
	teamsUserUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			teamsUserAllColumns,
			teamsUserColumnsWithDefault,
			teamsUserColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			teamsUserAllColumns,
			teamsUserPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert teams_users, could not build update column list")
		}

		ret := strmangle.SetComplement(teamsUserAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(teamsUserPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert teams_users, could not build conflict column list")
			}

			conflict = make([]string, len(teamsUserPrimaryKeyColumns))
			copy(conflict, teamsUserPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"teams_users\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(teamsUserType, teamsUserMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(teamsUserType, teamsUserMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert teams_users")
	}

	if !cached {
		teamsUserUpsertCacheMut.Lock()
		teamsUserUpsertCache[key] = cache
		teamsUserUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single TeamsUser record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *TeamsUser) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no TeamsUser provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), teamsUserPrimaryKeyMapping)
	sql := "DELETE FROM \"teams_users\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from teams_users")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for teams_users")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q teamsUserQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no teamsUserQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from teams_users")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for teams_users")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TeamsUserSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(teamsUserBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), teamsUserPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"teams_users\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, teamsUserPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from teamsUser slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for teams_users")
	}

	if len(teamsUserAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *TeamsUser) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindTeamsUser(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TeamsUserSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := TeamsUserSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), teamsUserPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"teams_users\".* FROM \"teams_users\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, teamsUserPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in TeamsUserSlice")
	}

	*o = slice

	return nil
}

// TeamsUserExists checks if the TeamsUser row exists.
func TeamsUserExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"teams_users\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if teams_users exists")
	}

	return exists, nil
}

// Exists checks if the TeamsUser row exists.
func (o *TeamsUser) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return TeamsUserExists(ctx, exec, o.ID)
}
