{
 "title": "AuthServiceDashboard",
 "description": "Service auth",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Auth CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "auth_service_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Auth Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "auth_service_memory_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Auth RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(auth_service_request_duration_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 8 },
   "targets": [
    { "expr": "auth_service_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Auth Request Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "targets": [
    {
     "expr": "auth_service_requests_error_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth Trraffic Outbound",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "sort_desc(auth_service_traffic_outbound_bytes_sum)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth Traffic Inbound",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "sort_desc(auth_service_traffic_inbound_bytes_sum)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "auth_service_new_users_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Wrong Password",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "auth_service_wrong_passwords_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}